rules:
  adhoc-packages:
    ignore:
      - 'publish.yml'
  cache-poisoning:
    ignore:
      - 'pyinstaller.yml'
  dangerous-triggers:
    ignore:
      - 'publish-msys2.yml'
      - 'publish-winget.yml'
      - 'release.yml'
  undocumented-permissions:
    disable: true
