jobs:
  build:
    container:
      image: 'ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-24.08'
      options: '--privileged'
    runs-on: '${{ matrix.system.image }}'
    steps:
      - uses: 'actions/checkout@v6.0.2'
      - id: 'flatpak_bundle'
        name: 'Set Flatpak bundle filename'
        run: |
          version=$(python3 -c "import tomllib; print(tomllib.load(open('pyproject.toml', 'rb'))['project']['version'])")
          echo "version=${version}" >> "$GITHUB_OUTPUT"
          echo "filename=sh.tat.youtube-unofficial-${version}-${{ matrix.system.arch }}.flatpak" >> "$GITHUB_OUTPUT"
      - name: 'Build Flatpak'
        uses: 'flatpak/flatpak-github-actions/flatpak-builder@v6.7'
        with:
          arch: '${{ matrix.system.arch }}'
          bundle: '${{ steps.flatpak_bundle.outputs.filename }}'
          manifest-path: 'sh.tat.youtube-unofficial.yml'
      - name: 'Upload Artifacts'
        uses: 'actions/upload-artifact@v7.0.1'
        with:
          if-no-files-found: 'error'
          name: 'sh.tat.youtube-unofficial-${{ steps.flatpak_bundle.outputs.version }}-${{ matrix.system.arch }}'
          path: '${{ steps.flatpak_bundle.outputs.filename }}'
      - name: 'Attest'
        uses: 'actions/attest@v4.1.0'
        with:
          subject-path: '${{ steps.flatpak_bundle.outputs.filename }}'
      - if: "github.ref_type == 'tag'"
        name: 'Upload package'
        uses: 'softprops/action-gh-release@v3.0.0'
        with:
          draft: true
          fail_on_unmatched_files: true
          files: '${{ steps.flatpak_bundle.outputs.filename }}'
    strategy:
      matrix:
        system:
          - arch: 'x86_64'
            image: 'ubuntu-latest'
          - arch: 'aarch64'
            image: 'ubuntu-24.04-arm'
name: 'Flatpak'
'on':
  push:
    branches:
      - 'master'
    paths:
      - 'youtube_unofficial/**'
      - '.github/workflows/flatpak.yml'
      - 'sh.tat.youtube-unofficial.yml'
      - 'pyproject.toml'
      - 'uv.lock'
      - 'poetry.lock'
    tags:
      - 'v*.*.*'
  workflow_dispatch: null
permissions:
  attestations: 'write'
  contents: 'write'
  id-token: 'write'
