jobs:
  spelling:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v6.0.2'
      - name: 'Check spelling'
        uses: 'streetsidesoftware/cspell-action@v8.4.0'
        with:
          check_dot_files: true
          suggestions: true
name: 'Spelling'
'on':
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'
permissions:
  contents: 'read'
