jobs:
  test:
    env:
      GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      HOMEBREW_NO_REQUIRE_TAP_TRUST: '1'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1'
        with:
          persist-credentials: false
      - name: 'Install uv'
        uses: 'astral-sh/setup-uv@ae62891fec2bb8e7d6c99fc78c9fec3a63790f8d'
      - name: 'Set up Python ${{ matrix.python-version }}'
        uses: 'actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97'
        with:
          python-version: '${{ matrix.python-version }}'
      - name: 'Install dependencies (uv)'
        run: 'uv sync --group tests --all-extras'
      - name: 'Install pytest-action dependencies'
        run: 'uv pip install pytest-md pytest-emoji'
      - name: 'Install dependencies (Yarn)'
        run: 'yarn'
      - name: 'Run tests'
        uses: 'pavelzw/pytest-action@510c5e90c360a185039bea56ce8b3e7e51a16507'
        with:
          click-to-expand: true
          custom-arguments: '--cov . --cov-branch --cov-report term-missing:skip-covered --cov-report xml'
          custom-pytest: 'yarn test'
          emoji: true
          job-summary: true
          report-title: 'Test Report'
          verbose: true
      - if: "github.event_name != 'pull_request'"
        name: 'Coverage'
        uses: 'coverallsapp/github-action@8d6379e14d29928660c4ba802d8e85393440b329'
        with:
          file: 'coverage.xml'
    strategy:
      matrix:
        python-version:
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
          - '3.14'
name: 'Tests'
'on':
  pull_request:
    branches:
      - 'master'
    paths:
      - 'youtube_unofficial/**'
      - '.github/workflows/tests.yml'
      - 'pyproject.toml'
      - 'uv.lock'
      - 'poetry.lock'
      - 'tests/**'
  push:
    branches:
      - 'master'
    paths:
      - 'youtube_unofficial/**'
      - '.github/workflows/tests.yml'
      - 'pyproject.toml'
      - 'uv.lock'
      - 'poetry.lock'
      - 'tests/**'
permissions:
  contents: 'read'
